* updated paths and removed some

diff --git a/.local/bin/cell2script b/.local/bin/cell2script
--- a/.local/bin/cell2script
+++ b/.local/bin/cell2script
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-# Copyright (C) 2023  jtmr05
+# Copyright (C) 2023-2024 jtmr05
 
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -13,102 +13,106 @@
 # GNU General Public License for more details.
 
 # You should have received a copy of the GNU General Public License
-# along with this program.  If not, see <https://www.gnu.org/licenses/>.
+# along with this program. If not, see <https://www.gnu.org/licenses/>.
 
-SCRIPT_NAME=cell2script
+SCRIPT_NAME="${0##*/}"
 
 usage(){
-    echo "Usage: $SCRIPT_NAME [OPTION] [--] FILE..."
-    echo "Convert Jupyter Notebook cell-style scripts to regular scripts"
-    echo ""
-    echo "Available options:"
-    echo "  -f    override existing output files"
-    echo "  -h    print this message and exit"
-    echo ""
-    echo "If '--' is passed in, all following arguments are interpreted as file names"
+    echo "Usage: $SCRIPT_NAME [OPTION]... [--] FILE..."
+    echo 'Convert Jupyter Notebook cell-style scripts to regular scripts.'
+    echo 'New files will be of the form {BASE_NAME}_script{.EXT}.'
+    echo ''
+    echo 'Available options:'
+    echo '  -f        override existing output files'
+    echo '  -h        print this message and exit'
+
+    exit 0
 }
+
+try(){
+    echo "Try '$SCRIPT_NAME -h' for more information" > /dev/stderr
+    exit 1
+}
+
+# load array manipulation utility functions
+. "$HOME/.local/lib/array.sh"
+
+# options
+force=0
+
+index=1; while [ "$index" -le $# ]; do
+
+    elem="$(eval "$(array_index "$index")")"
+    case "$elem" in
+        '-')
+            echo "$SCRIPT_NAME: warning: single dash ignored" > /dev/stderr
+            eval "$(array_remove "$index" "$@")"
+            ;;
+        -*)
+            eval "$(array_remove "$index" "$@")"
+            opts="${elem#-}"
+
+            while [ -n "$opts" ]; do
+                opt=$(printf '%c' "$opts")
+                case "$opt" in
+                    'f')
+                        force=1
+                        ;;
+                    'h')
+                        usage
+                        ;;
+                    '-')
+                        break 2
+                        ;;
+                    *)
+                        echo "$SCRIPT_NAME: '-$opt': unrecognized option" > /dev/stderr
+                        try
+                        ;;
+                esac
+                opts="${opts#"$opt"}"
+            done
+            ;;
+        *)
+            index=$((index+1))
+            ;;
+    esac
+done
+
+if [ $# -eq 0 ]; then
+    echo "$SCRIPT_NAME: missing operand" > /dev/stderr
+    try
+fi
 
 max(){
     [ "$1" -gt "$2" ] && return "$1"
     return "$2"
 }
 
-if [ $# -eq 0 ]; then
-    echo "$SCRIPT_NAME: missing operand"               > /dev/stderr
-    echo "Try '$SCRIPT_NAME -h' for more information." > /dev/stderr
-    exit 1
-fi
-
-force=0
-input_files=""
-has_sep=0
-
-for arg in "$@"; do
-
-    if [ $has_sep -eq 0 ]; then
-        case $arg in
-            '-f')
-                force=1
-                continue
-                ;;
-            '-h')
-                usage
-                exit 0
-                ;;
-            '--')
-                has_sep=1
-                continue
-                ;;
-            *)
-                ;;
-        esac
-    fi
-
-    input_files="$input_files
-        $arg"
-done
-
-input_files=$(perl -e '$_ = shift; s/^\s+//mg; print' "$input_files")
-
-IFS='
-'
 exit_code=0
-for f in $input_files; do
 
-    new_fn=$(perl -E '
+for f in "$@"; do
 
-        $base = q{};
-        $ext = q{.py};
-        $count = 1;
-
-        if($ARGV[0] =~ m/^(.+)(\..+)$/){
-            $base = $1;
-            $ext = $2;
-        }
-        else {
-            $base = shift;
-        }
-
-        print qq{${base}_script$ext};' "$f"
-    )
-
-    if ! [ -e "$f" ]; then
-        echo "$SCRIPT_NAME: $f: no such file or directory" > /dev/stderr
+    if [ ! -e "$f" ]; then
+        echo "$SCRIPT_NAME: '$f': no such file or directory" > /dev/stderr
         max "$exit_code" 2
         exit_code=$?
         continue
     fi
 
+    base_name="${f%.*}"
+    ext="${f##*.}"
+    new_fn="${base_name}_script.$ext"
+
     if [ "$force" -eq 0 ] && [ -e "$new_fn" ]; then
-        echo "$SCRIPT_NAME: $new_fn: file exists"          > /dev/stderr
+        echo "$SCRIPT_NAME: '$new_fn': file exists" > /dev/stderr
         max "$exit_code" 3
         exit_code=$?
         continue
     fi
 
     echo '#!/usr/bin/env python3' > "$new_fn"
-    perl -pe 's/^## (BEGIN|END).*$//' "$f" >> "$new_fn"
-    autopep8 -i "$new_fn"
+    perl -pe 's/^\s*##\s*(BEGIN|END).*$//' "$f" | autopep8 - >> "$new_fn"
+    #autopep8 -i "$new_fn"
     chmod +x "$new_fn"
 done
 
diff --git a/.local/bin/my-i3exit b/.local/bin/my-i3exit
--- a/.local/bin/my-i3exit
+++ b/.local/bin/my-i3exit
@@ -1,6 +1,6 @@
-#!/bin/bash
+#!/bin/sh
 
-# Copyright (C) 2023  jtmr05
+# Copyright (C) 2023-2024 jtmr05
 
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -13,10 +13,90 @@
 # GNU General Public License for more details.
 
 # You should have received a copy of the GNU General Public License
-# along with this program.  If not, see <https://www.gnu.org/licenses/>.
+# along with this program. If not, see <https://www.gnu.org/licenses/>.
 
-# with openrc use loginctl
-[ "$(cat /proc/1/comm)" = "systemd" ] && logind=systemctl || logind=loginctl
+SCRIPT_NAME="${0##*/}"
+
+usage(){
+    echo "Usage: $SCRIPT_NAME [OPTION] [--] ACTION"
+    echo 'Perform the exit ACTION on the system.'
+    echo ''
+    echo 'Available actions:'
+    echo '  hibernate'
+    echo '  lock'
+    echo '  logout'
+    echo '  reboot'
+    echo '  shutdown'
+    echo '  suspend'
+    echo ''
+    echo 'Available options:'
+    echo '  -h        print this message and exit'
+    echo '  -n        get notification message'
+
+    exit 0
+}
+
+try(){
+    echo "Try '$SCRIPT_NAME -h' for more information" > /dev/stderr
+    exit 1
+}
+
+notif_msg(){
+    echo '• (h)ibernate\n• (l)ock\n• l(o)gout\n• (r)eboot\n• (s)hutdown\n• s(u)spend'
+    exit 0
+}
+
+# load array manipulation utility functions
+. "$HOME/.local/lib/array.sh"
+
+index=1; while [ "$index" -le $# ]; do
+
+    elem="$(eval "$(array_index "$index")")"
+    case "$elem" in
+        '-')
+            echo "$SCRIPT_NAME: warning: single dash ignored" > /dev/stderr
+            eval "$(array_remove "$index" "$@")"
+            ;;
+        -*)
+            eval "$(array_remove "$index" "$@")"
+            opts="${elem#-}"
+
+            while [ -n "$opts" ]; do
+                opt=$(printf '%c' "$opts")
+                case "$opt" in
+                    'h')
+                        usage
+                        ;;
+                    'n')
+                        notif_msg                        
+                        ;;
+                    *)
+                        echo "$SCRIPT_NAME: '-$opt': unrecognized option" > /dev/stderr
+                        try
+                        ;;
+                esac
+                # unreachable with current options available
+                # commented out to keep ShellCheck happy
+                # opts="${opts#"$opt"}"
+            done
+            ;;
+        *)
+            index=$((index+1))
+            ;;
+    esac
+done
+
+if [ $# -eq 0 ]; then
+    echo "$SCRIPT_NAME: missing operand" > /dev/stderr
+    try
+fi
+
+if [ $# -gt 1 ]; then
+    echo "$SCRIPT_NAME: '$2': extra operand" > /dev/stderr
+    try
+fi
+
+logind=systemctl
 
 case "$1" in
     lock)
@@ -25,26 +105,16 @@ case "$1" in
     logout)
         i3-msg exit
         ;;
-    switch_user)
-        dm-tool switch-to-greeter
-        ;;
     suspend)
         my-blurlock && $logind suspend
         ;;
-    #hibernate)
-    #    my-blurlock && $logind hibernate
-    #    ;;
+    hibernate)
+        my-blurlock && $logind hibernate
+        ;;
     reboot)
         $logind reboot
         ;;
     shutdown)
         $logind poweroff
         ;;
-    *)
-        echo "== ! i3exit: missing or invalid argument ! =="
-        #echo "Try again with: lock | logout | switch_user | suspend | hibernate | reboot | shutdown"
-        echo "Try again with: lock | logout | switch_user | suspend | reboot | shutdown"
-        exit 2
 esac
-
-exit 0
diff --git a/.local/bin/my-volume-mixer b/.local/bin/my-volume-mixer
--- a/.local/bin/my-volume-mixer
+++ b/.local/bin/my-volume-mixer
@@ -1,6 +1,6 @@
-#!/usr/bin/env perl
+#!/bin/sh
 
-# Copyright (C) 2023  jtmr05
+# Copyright (C) 2023-2024 jtmr05
 
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -13,90 +13,175 @@
 # GNU General Public License for more details.
 
 # You should have received a copy of the GNU General Public License
-# along with this program.  If not, see <https://www.gnu.org/licenses/>.
+# along with this program. If not, see <https://www.gnu.org/licenses/>.
 
-use v5.36;
+SCRIPT_NAME="${0##*/}"
 
-use constant LOW_VOLUME_ICON 	=> 'audio-volume-low';
-use constant MEDIUM_VOLUME_ICON => 'audio-volume-medium';
-use constant HIGH_VOLUME_ICON 	=> 'audio-volume-high';
-use constant MUTED_VOLUME_ICON 	=> 'audio-volume-muted';
+LOW_VOLUME_ICON='audio-volume-low'
+MEDIUM_VOLUME_ICON='audio-volume-medium'
+HIGH_VOLUME_ICON='audio-volume-high'
+MUTED_VOLUME_ICON='audio-volume-muted'
 
-use constant LOW_VOLUME 		=> 35;
-use constant HIGH_VOLUME 		=> 75;
+LOW_VOLUME=35
+HIGH_VOLUME=75
 
-use constant PROGRESS_BAR_LEN	=> 23;
-use constant FULL_BOCK			=> '▄';
-use constant EMPTY_BOCK			=> '▁';
+PROGRESS_BAR_LEN=23
+FULL_BOCK='▄'
+EMPTY_BOCK='▁'
 
+usage(){
+    echo "Usage: $SCRIPT_NAME [OPTION]... OPERAND"
+    echo 'Simple Pulseaudio output volume management.'
+    echo ''
+    echo 'Available operands:'
+    echo '  mute'
+    echo '  unmute'
+    echo '  toggle    toggle between muted and unmuted'
+    echo '  [+|-]NUM  set volume to, increase by, or decrease by NUM'
+    echo '            according to the given sign or lack thereof'
+    echo ''
+    echo 'Availabe options:'
+    echo '  -h        print this message and exit'
 
-sub main(){
-
-	if(scalar @ARGV == 0){
-		say STDERR "$0: missing operand\n"
-		. "usage: $0 [OPTION]\n\n"
-		. "available options:\n"
-		. "  NUM\t\tset volume to NUM\n"
-		. "  +NUM\t\tincrease volume by NUM\n"
-		. "  -NUM\t\tdecrease volume by NUM\n"
-		. "  mute\t\tmute volume\n"
-		. "  unmute\tunmute volume\n"
-		. "  toggle\ttoggle between muted and unmuted";
-
-		return 1;
-	}
-
-	my $arg = shift @ARGV;
-
-	if($arg =~ m/^(\d+)$/){
-		system "pamixer --set-volume $1";
-	}
-	elsif($arg =~ m/^\+(\d+)$/){
-		system "pamixer -i $1";
-	}
-	elsif($arg =~ m/^\-(\d+)$/){
-		system "pamixer -d $1";
-	}
-	elsif($arg =~ m/^toggle$/){
-		system 'pamixer -t';
-	}
-	elsif($arg =~ m/^mute$/){
-		system 'pamixer -m';
-	}
-	elsif($arg =~ m/^unmute$/){
-		system 'pamixer -u';
-	}
-	else {
-		say STDERR "$0: invalid option: '$arg'";
-		return 2;
-	}
-
-
-	my $volume = substr `pamixer --get-volume`, 0, -1;
-	my $is_muted = `pamixer --get-volume-human` eq "muted\n";
-
-	my $icon = MEDIUM_VOLUME_ICON;
-
-	$icon = LOW_VOLUME_ICON   if($volume < LOW_VOLUME);
-	$icon = HIGH_VOLUME_ICON  if($volume > HIGH_VOLUME);
-	$icon = MUTED_VOLUME_ICON if($is_muted);
-
-
-	my $progress_bar = '';
-	my $full_blocks_end_index = int $volume / 100 * PROGRESS_BAR_LEN - 1;
-
-	foreach(0..$full_blocks_end_index){
-		$progress_bar .= FULL_BOCK;
-	}
-
-	foreach(($full_blocks_end_index + 1)..(PROGRESS_BAR_LEN - 1)){
-		$progress_bar .= EMPTY_BOCK;
-	}
-
-	system "notify-send -r 777 --app-name=$0 -i $icon 'Volume' '$volume%\n$progress_bar' &";
-	return 0;
+    exit 0
 }
 
-unless(caller){
-	exit main();
+try(){
+    echo "Try '$SCRIPT_NAME -h' for more information" > /dev/stderr
+    exit 1
 }
+
+# https://unix.stackexchange.com/questions/598036/how-to-check-if-variable-is-integer-avoid-problem-with-spaces-around-in-posix
+# 1 is false in shell scripting!
+is_integer(){
+    case "${1#[+-]}" in
+        *[!0-9]*)
+            return 1
+            ;;
+        '')
+            return 1
+            ;;
+        *)
+            return 0
+            ;;
+    esac
+}
+
+# load array manipulation utility functions
+. "$HOME/.local/lib/array.sh"
+
+index=1; while [ "$index" -le $# ]; do
+
+    elem="$(eval "$(array_index "$index")")"
+    case "$elem" in
+        '-')
+            echo "$SCRIPT_NAME: warning: single dash ignored" > /dev/stderr
+            eval "$(array_remove "$index" "$@")"
+            ;;
+        -*)
+            if is_integer "$elem"; then
+                index=$((index + 1))
+                continue
+            fi
+            eval "$(array_remove "$index" "$@")"
+            opts="${elem#-}"
+
+            while [ -n "$opts" ]; do
+                opt=$(printf '%c' "$opts")
+                case "$opt" in
+                    'h')
+                        usage
+                        ;;
+                    *)
+                        echo "$SCRIPT_NAME: '-$opt': unrecognized option" > /dev/stderr
+                        try
+                        ;;
+                esac
+                # unreachable with current options available
+                # commented out to keep ShellCheck happy
+                #opts="${opts#"$opt"}"
+            done
+            ;;
+        *)
+            index=$((index + 1))
+            ;;
+    esac
+done
+
+if [ $# -eq 0 ]; then
+    echo "$SCRIPT_NAME: missing operand" > /dev/stderr
+    try
+fi
+
+if [ $# -gt 1 ]; then
+    echo "$SCRIPT_NAME: '$2': extra operand" > /dev/stderr
+    try
+fi
+
+# prints the volume after handling and
+# returns wether it is muted or not
+handle_arg(){
+    case "$1" in
+        'mute')
+            pamixer -m
+            ;;
+        'unmute')
+            pamixer -u
+            ;;
+        'toggle')
+            pamixer -t
+            ;;
+        *)
+            is_integer "$1" || { echo "$SCRIPT_NAME: '$1': invalid operand" && exit 2; }
+            sign=$(printf '%c' "$1")
+            arg="${1#[+-]}"
+
+            case "$sign" in
+                '+')
+                    pamixer -i "$arg"
+                    ;;
+                '-')
+                    pamixer -d "$arg"
+                    ;;
+                *)
+                    pamixer --set-volume "$arg"
+                    ;;
+            esac
+            ;;
+    esac > /dev/null
+
+    # print volume
+    pamixer --get-volume
+    { [ "$(pamixer --get-volume-human)" = 'muted' ] && return 0; } || return 1
+}
+
+volume="$(handle_arg "$1")"
+is_muted=$?
+
+if [ "$is_muted" -eq 0 ]; then
+    icon="$MUTED_VOLUME_ICON"
+elif [ "$volume" -le "$LOW_VOLUME" ]; then
+    icon="$LOW_VOLUME_ICON"
+elif [ "$volume" -ge "$HIGH_VOLUME" ]; then
+    icon="$HIGH_VOLUME_ICON"
+else
+    icon="$MEDIUM_VOLUME_ICON"
+fi
+
+blocks_end=$((volume * PROGRESS_BAR_LEN / 100))
+
+index=0; while [ "$index" -lt "$blocks_end" ]; do
+    progress_bar="${progress_bar}$FULL_BOCK"
+    index=$((index + 1))
+done
+
+while [ "$index" -lt "$PROGRESS_BAR_LEN" ]; do
+    progress_bar="${progress_bar}$EMPTY_BOCK"
+    index=$((index + 1))
+done
+
+echo "$progress_bar" >&2
+
+# FIXME use -p to get notification id and then replace subsquent notifications that way
+# perhaps using a "global" named FIFO
+exec notify-send -r 777 --app-name="$SCRIPT_NAME" -i "$icon" 'Volume' "$volume%\n$progress_bar"
diff --git a/.local/bin/silent b/.local/bin/silent
--- a/.local/bin/silent
+++ b/.local/bin/silent
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-# Copyright (C) 2023  jtmr05
+# Copyright (C) 2023-2025 jtmr05
 
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -13,35 +13,129 @@
 # GNU General Public License for more details.
 
 # You should have received a copy of the GNU General Public License
-# along with this program.  If not, see <https://www.gnu.org/licenses/>.
+# along with this program. If not, see <https://www.gnu.org/licenses/>.
 
-SCRIPT_NAME=silent
+SCRIPT_NAME="${0##*/}"
 
 usage(){
-    echo "Usage: $SCRIPT_NAME PROG [ARGS]..."
-    echo "Silently execute PROG with arguments ARGS"
-    echo ""
-    echo "Available options: "
-    echo  "  -h, --help      print this message and exit"
+    echo "Usage: $SCRIPT_NAME [OPTION]... [--] PROG [ARGS]..."
+    echo "   or: $SCRIPT_NAME [OPTION]... COMMAND_STRING"
+    echo 'Silently execute PROG with arguments ARGS.'
+    echo ''
+    echo 'Available options:'
+    echo '  -e FILE   redirect stderr to FILE'
+    echo '  -h        print this message and exit'
+    echo '  -o FILE   redirect stdout to FILE'
+
+    exit 0
 }
 
-if [ $# -eq 0 ]; then
-    echo "$SCRIPT_NAME: missing operand"                  > /dev/stderr
-    echo "Try '$SCRIPT_NAME --help' for more information" > /dev/stderr
+try(){
+    echo "Try '$SCRIPT_NAME -h' for more information" > /dev/stderr
     exit 1
-fi
+}
 
+# load array manipulation utility functions
+. "$HOME/.local/lib/array.sh"
 
-cmd=""
+# options
+out_file=/dev/null
+err_file=/dev/null
 
-for arg in "$@"; do
-    if [ "$arg" = '-h' ] || [ "$arg" = '--help' ]; then
-        exit 0
-    else
-        cmd="$cmd $arg"
-    fi
+index=1; while [ "$index" -le $# ]; do
+
+    elem="$(eval "$(array_index "$index")")"
+    case "$elem" in
+        '-')
+            echo "$SCRIPT_NAME: warning: single dash ignored" > /dev/stderr
+            eval "$(array_remove "$index" "$@")"
+            ;;
+        -*)
+            eval "$(array_remove "$index" "$@")"
+            opts="${elem#-}"
+
+            while [ -n "$opts" ]; do
+                opt=$(printf '%c' "$opts")
+                case "$opt" in
+                    'e')
+                        elem="$(eval "$(array_index "$index")")"
+                        if [ -z "$elem" ]; then
+                            echo "$SCRIPT_NAME: '-$opt': option requires an argument" > /dev/stderr
+                            try
+                        fi
+                        eval "$(array_remove "$index" "$@")"
+                        err_file="$elem"
+                        ;;
+                    'h')
+                        usage
+                        ;;
+                    'o')
+                        elem="$(eval "$(array_index "$index")")"
+                        if [ -z "$elem" ]; then
+                            echo "$SCRIPT_NAME: '-$opt': option requires an argument" > /dev/stderr
+                            try
+                        fi
+                        eval "$(array_remove "$index" "$@")"
+                        out_file="$elem"
+                        ;;
+                    '-')
+                        break 2
+                        ;;
+                    *)
+                        echo "$SCRIPT_NAME: '-$opt': unrecognized option" > /dev/stderr
+                        try
+                        ;;
+                esac
+                opts="${opts#"$opt"}"
+            done
+            ;;
+        *)
+            index=$((index+1))
+            ;;
+    esac
 done
 
-sh -c "$cmd > /dev/null 2> /dev/null &"
+if [ $# -eq 0 ]; then
+    echo "$SCRIPT_NAME: missing operand" > /dev/stderr
+    try
+fi
 
-# TODO port to perl (shell sucks!)
+# if ! command -v "$1" > /dev/null 2>&1; then
+#     echo "$SCRIPT_NAME: '$1': command not found" > /dev/stderr
+#     exit 2
+# fi
+
+exit_val=0
+
+[ -e "$out_file" ] || touch "$out_file" || {
+    echo "$SCRIPT_NAME: '$out_file': cannot create file" &&
+    out_file=/dev/null &&
+    exit_val=3
+}
+
+[ -e "$err_file" ] || touch "$err_file" || {
+    echo "$SCRIPT_NAME: '$err_file': cannot create file" &&
+    err_file=/dev/null &&
+    exit_val=3
+}
+
+[ -w "$out_file" ] || {
+    echo "$SCRIPT_NAME: '$out_file': no write permission" &&
+    out_file=/dev/null &&
+    exit_val=4
+}
+
+[ -w "$err_file" ] || {
+    echo "$SCRIPT_NAME: '$err_file': no write permission" &&
+    err_file=/dev/null &&
+    exit_val=4
+}
+
+# nohup "$@" > "$out_file" 2> "$err_file" &
+
+# FIXME properly handle shell operators in $@
+# set -x
+sh -c "{ $*; } > '$out_file' 2> '$err_file' &"
+# set +x
+
+exit "$exit_val"
